# Generated by Django 6.0.4 on 2026-07-08 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0018_post_softdelete_emailverification"),
    ]

    operations = [
        # The Design index was already created with the hash-based name in the DB
        # (DB was originally set up with Django 6.0). Only update the migration
        # state so Django stops complaining — no SQL is executed.
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.RenameIndex(
                    model_name="design",
                    new_name="core_design_user_id_13e9d8_idx",
                    old_name="core_design_user_id_source_idx",
                ),
            ],
        ),
        # EmailVerification index was explicitly named in 0018, so this rename
        # runs for real in the DB.
        migrations.RenameIndex(
            model_name="emailverification",
            new_name="core_emailv_token_606d0a_idx",
            old_name="core_emailv_token_idx",
        ),
    ]
